# Métodos iterativos para solução de sistemas lineares

In [1]:
import numpy as np

In [36]:
# Vamos resolver o sistema linear Mx = b.
# Para isto, declaramos a matriz M e o vetor b
M = np.array([
    [-5.1, 2, 3],
    [5, 8, 2],
    [1, 0, 3],
])
b = np.array([1, 2, 3])

In [37]:
# Encontramos a resposta explicitamente como referência
np.linalg.solve(M, b)

array([ 0.27842227, -0.15081206,  0.90719258])

## Método de Jacobi

In [38]:
# Extraímos a matriz diagonal inversa
Dinv = np.diag(1 / np.diag(M))
D = np.diag(np.diag(M))

print('diagonal inversa:')
print(Dinv)

diagonal inversa:
[[-0.19607843  0.          0.        ]
 [ 0.          0.125       0.        ]
 [ 0.          0.          0.33333333]]


In [39]:
# Extraímos a matriz R
R = M - D

print('matriz resto:')
print(R)

matriz resto:
[[ 0.  2.  3.]
 [ 5.  0.  2.]
 [ 1.  0.  0.]]


In [42]:
# Escolhemos um chute inicial
x = [ 12., -14.,  -3.]

# Iteramos várias vezes
for i in range(100):
    y = np.dot(Dinv, (b - np.dot(R, x)))
    delta = np.sum(np.abs(x - y))
    if delta < 1e-3:
        break
    x = y
    print('iteração', i)
    print(x)

iteração 0
[-7.45098039 -6.5        -3.        ]
iteração 1
[-4.50980392  5.65686275  3.48366013]
iteração 2
[ 4.07151096  2.19771242  2.50326797]
iteração 3
[ 2.13828015 -2.92051134 -0.35717032]
iteração 4
[-1.55147718 -0.99713251  0.28723995]
iteração 5
[-0.41814611  1.14786325  1.51715906]
iteração 6
[ 1.14651053  0.13205156  1.13938204]
iteração 7
[ 0.52593122 -0.75141459  0.61782982]
iteração 8
[-0.12732151 -0.23316447  0.82468959]
iteração 9
[ 0.19759605  0.12340355  1.0424405 ]
iteração 10
[ 0.46551541 -0.13410766  0.93413465]
iteração 11
[ 0.3008213 -0.2744808  0.8448282]
iteração 12
[ 0.1932398  -0.14922036  0.89972623]
iteração 13
[ 0.2746545  -0.09570644  0.93558673]
iteração 14
[ 0.31673477 -0.15555575  0.9084485 ]
iteração 15
[ 0.27730078 -0.17507136  0.89442174]
iteração 16
[ 0.26139657 -0.14691843  0.90756641]
iteração 17
[ 0.28016909 -0.14026446  0.91286781]
iteração 18
[ 0.28589696 -0.15332263  0.9066103 ]
iteração 19
[ 0.27709522 -0.15533818  0.90470101]
iteração 20
[

## Função para resolver sistemas lineares

In [46]:
def solve(M, b, max_iter=100, tol=1e-5):
    """
    Resolve o sistema linear M x = b, retornando x.
    
    Utiliza o método de Jacobi.
    """
    M = np.asarray(M)
    b = np.asarray(b)
    
    # Extrai D, Dinv e R
    diagonal_vector = np.diag(M)
    D = np.diag(diagonal_vector)
    Dinv = np.diag(1 /  diagonal_vector)
    R = M - D
    
    # Realiza o loop principal
    x = b
    for i in range(max_iter):
        x_ = np.dot(Dinv, (b - np.dot(R, x)))
        if np.mean(np.abs(x - x_)) < tol:
            return x_
        x = x_
    raise ValueError('método não convergiu!')

In [47]:
solve(M, b)

array([ 0.27842366, -0.15081033,  0.90719361])